-- ===========================
-- BANCO DE DADOS: MINDTRACK
-- ===========================

-- === DROPS (ordem reversa para evitar conflitos) ===
DROP TABLE t_mt_usuario_badges CASCADE CONSTRAINTS;
DROP TABLE t_mt_badges CASCADE CONSTRAINTS;
DROP TABLE t_mt_habitos CASCADE CONSTRAINTS;
DROP TABLE t_mt_alertas_ia CASCADE CONSTRAINTS;
DROP TABLE t_mt_sprints CASCADE CONSTRAINTS;
DROP TABLE t_mt_humor CASCADE CONSTRAINTS;
DROP TABLE t_mt_usuarios CASCADE CONSTRAINTS;

-- =========================================
-- TABELA: t_mt_usuarios
-- =========================================
CREATE TABLE t_mt_usuarios (
    id_usuario       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(100) NOT NULL,
    email            VARCHAR(150) UNIQUE NOT NULL,
    senha_hash       VARCHAR(255) NOT NULL,
    perfil           VARCHAR(20) CHECK (perfil IN ('PROFISSIONAL', 'GESTOR')) NOT NULL,
    data_cadastro    DATE DEFAULT CURRENT_DATE,
    empresa          VARCHAR(100)
);

-- =========================================
-- TABELA: t_mt_humor
-- =========================================
CREATE TABLE t_mt_humor (
    id_humor         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT NOT NULL,
    data_registro    DATE DEFAULT CURRENT_DATE,
    nivel_humor      NUMBER(1) CHECK (nivel_humor BETWEEN 1 AND 5),
    nivel_energia    NUMBER(1) CHECK (nivel_energia BETWEEN 1 AND 5),
    comentario       VARCHAR(255),
    CONSTRAINT fk_humor_usuario FOREIGN KEY (id_usuario)
        REFERENCES t_mt_usuarios (id_usuario)
        ON DELETE CASCADE
);

-- =========================================
-- TABELA: t_mt_sprints
-- =========================================
CREATE TABLE t_mt_sprints (
    id_sprint        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT NOT NULL,
    nome_sprint      VARCHAR(100) NOT NULL,
    data_inicio      DATE NOT NULL,
    data_fim         DATE,
    produtividade    NUMBER(5,2),
    tarefas_concluidas INT,
    commits          INT,
    CONSTRAINT fk_sprint_usuario FOREIGN KEY (id_usuario)
        REFERENCES t_mt_usuarios (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT uq_sprint_usuario_nome UNIQUE (id_usuario, nome_sprint)
);

-- =========================================
-- TABELA: t_mt_alertas_ia
-- =========================================
CREATE TABLE t_mt_alertas_ia (
    id_alerta        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT NOT NULL,
    data_alerta      DATE DEFAULT CURRENT_DATE,
    tipo_alerta      VARCHAR(50) NOT NULL,
    mensagem         VARCHAR(255),
    nivel_risco      NUMBER(1) CHECK (nivel_risco BETWEEN 1 AND 5),
    CONSTRAINT fk_alerta_usuario FOREIGN KEY (id_usuario)
        REFERENCES t_mt_usuarios (id_usuario)
        ON DELETE CASCADE
);

-- =========================================
-- TABELA: t_mt_habitos
-- =========================================
CREATE TABLE t_mt_habitos (
    id_habito        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT NOT NULL,
    tipo_habito      VARCHAR(50) NOT NULL,   -- Ex: "Hidratação", "Pausa ativa", "Meditação"
    data_habito      DATE DEFAULT CURRENT_DATE,
    pontuacao        INT DEFAULT 0,
    CONSTRAINT fk_habito_usuario FOREIGN KEY (id_usuario)
        REFERENCES t_mt_usuarios (id_usuario)
        ON DELETE CASCADE
);

-- =========================================
-- TABELA: t_mt_badges
-- =========================================
CREATE TABLE t_mt_badges (
    id_badge         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_badge       VARCHAR(50) NOT NULL,   -- Ex: "Equilíbrio Mental", "Dev Zen"
    descricao        VARCHAR(150),
    pontos_requeridos INT NOT NULL CHECK (pontos_requeridos >= 0)
);

-- =========================================
-- TABELA: t_mt_usuario_badges
-- =========================================
CREATE TABLE t_mt_usuario_badges (
    id_usuario       INT NOT NULL,
    id_badge         INT NOT NULL,
    data_conquista   DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (id_usuario, id_badge),
    CONSTRAINT fk_usuario_badge_usuario FOREIGN KEY (id_usuario)
        REFERENCES t_mt_usuarios (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_badge_badge FOREIGN KEY (id_badge)
        REFERENCES t_mt_badges (id_badge)
        ON DELETE CASCADE
);

