// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using nexus.Data;

#nullable disable

namespace nexus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nexus.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Empresa")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMPRESA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PERFIL");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("T_MT_USUARIOS", (string)null);
                });

            modelBuilder.Entity("nexus.Models.Humor", b =>
                {
                    b.Property<int>("IdHumor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HUMOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHumor"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("COMENTARIO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("NivelEnergia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_ENERGIA");

                    b.Property<int>("NivelHumor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_HUMOR");

                    b.HasKey("IdHumor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_MT_HUMOR", (string)null);
                });

            modelBuilder.Entity("nexus.Models.Sprint", b =>
                {
                    b.Property<int>("IdSprint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SPRINT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSprint"));

                    b.Property<int?>("Commits")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COMMITS");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("NomeSprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME_SPRINT");

                    b.Property<decimal?>("Produtividade")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("PRODUTIVIDADE");

                    b.Property<int?>("TarefasConcluidas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TAREFAS_CONCLUIDAS");

                    b.HasKey("IdSprint");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_MT_SPRINTS", (string)null);
                });

            modelBuilder.Entity("nexus.Models.AlertaIA", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_MT_ALERTAS_IA", (string)null);
                });

            modelBuilder.Entity("nexus.Models.Habito", b =>
                {
                    b.Property<int>("IdHabito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HABITO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabito"));

                    b.Property<DateTime>("DataHabito")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HABITO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTUACAO");

                    b.Property<string>("TipoHabito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_HABITO");

                    b.HasKey("IdHabito");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_MT_HABITOS", (string)null);
                });

            modelBuilder.Entity("nexus.Models.Badge", b =>
                {
                    b.Property<int>("IdBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BADGE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBadge"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomeBadge")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME_BADGE");

                    b.Property<int>("PontosRequeridos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTOS_REQUERIDOS");

                    b.HasKey("IdBadge");

                    b.ToTable("T_MT_BADGES", (string)null);
                });

            modelBuilder.Entity("nexus.Models.UsuarioBadge", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("IdBadge")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BADGE");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONQUISTA");

                    b.HasKey("IdUsuario", "IdBadge");

                    b.HasIndex("IdBadge");

                    b.ToTable("T_MT_USUARIO_BADGES", (string)null);
                });

            modelBuilder.Entity("nexus.Models.Humor", b =>
                {
                    b.HasOne("nexus.Models.Usuario", "Usuario")
                        .WithMany("Humores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("nexus.Models.Sprint", b =>
                {
                    b.HasOne("nexus.Models.Usuario", "Usuario")
                        .WithMany("Sprints")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("nexus.Models.AlertaIA", b =>
                {
                    b.HasOne("nexus.Models.Usuario", "Usuario")
                        .WithMany("AlertasIA")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("nexus.Models.Habito", b =>
                {
                    b.HasOne("nexus.Models.Usuario", "Usuario")
                        .WithMany("Habitos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("nexus.Models.UsuarioBadge", b =>
                {
                    b.HasOne("nexus.Models.Badge", "Badge")
                        .WithMany("UsuarioBadges")
                        .HasForeignKey("IdBadge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nexus.Models.Usuario", "Usuario")
                        .WithMany("UsuarioBadges")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("nexus.Models.Badge", b =>
                {
                    b.Navigation("UsuarioBadges");
                });

            modelBuilder.Entity("nexus.Models.Usuario", b =>
                {
                    b.Navigation("AlertasIA");

                    b.Navigation("Habitos");

                    b.Navigation("Humores");

                    b.Navigation("Sprints");

                    b.Navigation("UsuarioBadges");
                });
#pragma warning restore 612, 618
        }
    }
}
